### PR TITLE
fix(sass): #286 inject the correct path based on vuetify version.

### LINKED ISSUE #286: Adding variables.scss file to freshly created Vuetify project causes SassError: Can't find stylesheet to import.
### Environment
Vuetify Version: 3.0.0-alpha
@vue/cli Version: 4.5.13
Browsers: Google Chrome
OS: Ubuntu 20.04

### Steps to reproduce
Create a test app (with Typescript and CSS preprocessor support) and add Vuetify v3 alpha.

`vue create test-app`
`cd test-app`
`vue add vuetify`
`npm run build`
You should see a successful build.

Add a styles/variables.scss with anything in it:
`mkdir src/styles; echo '$font-size-root: 18px;' > src/styles/variables.scss`

Re-run the build:
`npm run build`

Observe the failure of the build with many errors:
```
 ERROR  Failed to compile with 39 errors                                                                                                     9:24:37 AM

 error  in ./node_modules/vuetify/lib/components/VAlert/VAlert.sass

SassError: Can't find stylesheet to import.
  ╷
2 │ @import '~vuetify/src/styles/styles.sass'
  │         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  ╵
  node_modules/vuetify/lib/components/VAlert/VAlert.sass 2:9  root stylesheet
  ```

Also observe that if you remove the variables.scss file, the build returns to normal and is successful again.

### Expected Behavior
As the docs say, the addition of the variables.scss file should perform as expected and allow global replacement of vuetify stylings.

### Actual Behavior
Can no longer compile the project.

### Other comments
I have not found a workaround for this but I am no expert in webpack or SASS.  On a suggestion in the Vuetify discord I tried adding
`@import '~vuetify/lib/styles/styles.sass'`
to the variables file but it had no effect.

### PR DESCRIPTION
**Pull request by ElijahKotyluk**
## Description

Closes #286 

## Motivation and Context

Fix #286 

## How Has This Been Tested?

CLI

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Improvement/refactoring (non-breaking change that doesn't add any features but makes things better)

## Checklist:

- [x] The PR title is no longer than 64 characters.
- [x] The PR is submitted to the correct branch (`master` for bug fixes, `dev` for new features and backwards compatible changes).
- [x] My code follows the code style of this project.

### CODE REVIEW

File: packages/vue-cli-plugin-vuetify/util/helpers.js [hunk 1]
```diff
@@ -32,6 +32,19 @@ function fileExists (api, file) {
   return fs.existsSync(api.resolve(file))
 }
 
+// Returns the correct path for styles based on the Vuetify version
+function determineStylesPath(end) {
```
Comment (johnleider) [inline packages/vue-cli-plugin-vuetify/util/helpers.js:36]: might be splitting hairs, but what about `getStylesPath`? It's the typical language that we use in Vuetify.

**Review by johnleider — APPROVED** [review]

File: packages/vue-cli-plugin-vuetify/util/helpers.js (hunk 1 above)
Comment (ElijahKotyluk) [reply packages/vue-cli-plugin-vuetify/util/helpers.js:36]: Let's do it, I was having trouble coming up with a name tbh lol
